# Example secrets for the dashboard on Streamlit Cloud

# Map project names to their deployed URLs
# Copy the contents into Streamlit Cloud's Secrets (without comments),
# or save as .streamlit/secrets.toml for local testing.

[APP_URLS]
Project1 = "https://your-user-your-repo-project1.streamlit.app"
Project2 = "https://your-user-your-repo-project2.streamlit.app"
Project3 = "https://github.com/nolanrd04/streamlit_projects/blob/main/Project3/app.py"
Project4 = "https://your-user-your-repo-project4.streamlit.app"
Project5 = "https://your-user-your-repo-project5.streamlit.app"
Project6 = "https://your-user-your-repo-project6.streamlit.app"
Project7 = "https://your-user-your-repo-project7.streamlit.app"
Project8 = "https://your-user-your-repo-project8.streamlit.app"
Project9 = "https://your-user-your-repo-project9.streamlit.app"
Project10 = "https://your-user-your-repo-project10.streamlit.app"
